//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsDataCore.Mods.Seg
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAS
    {
        public int ID { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public Nullable<System.DateTime> FECNACIMIENTO { get; set; }
        public string RNC { get; set; }
        public string TIPORNC { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONO { get; set; }
        public string CELULAR { get; set; }
        public string GENERO { get; set; }
        public string ESTATUSMARITAL { get; set; }
        public string OCUPACION { get; set; }
        public string RELIGION { get; set; }
        public Nullable<System.DateTime> FECCREACION { get; set; }
        public Nullable<System.DateTime> ULTIMAVISITA { get; set; }
        public bool ESTATUS { get; set; }
        public string AUTOR { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<int> AUTORID { get; set; }
        public Nullable<int> PAISID { get; set; }
    
        public virtual AUTORES AUTORES { get; set; }
        public virtual AUTORES AUTORES1 { get; set; }
        public virtual PAISES PAISES { get; set; }
    }
}
