//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsDataCore.Mods.Seg
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOSSEG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOSSEG()
        {
            this.ROLESUSUARIO = new HashSet<ROLESUSUARIO>();
        }
    
        public int ID { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> FECCREACION { get; set; }
        public Nullable<System.DateTime> ULTIMAVISITA { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string NIVEL { get; set; }
        public bool ESTATUS { get; set; }
        public string AUTOR { get; set; }
        public Nullable<int> AUTORID { get; set; }
        public Nullable<int> SUCURSALID { get; set; }
    
        public virtual AUTORES AUTORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROLESUSUARIO> ROLESUSUARIO { get; set; }
    }
}
