//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Core.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Core.Data.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with {0}.
        /// </summary>
        public static string ChatPageTitle {
            get {
                return ResourceManager.GetString("ChatPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string ChatPageTitleOnHold {
            get {
                return ResourceManager.GetString("ChatPageTitleOnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string ConnectAsAdminButtonText {
            get {
                return ResourceManager.GetString("ConnectAsAdminButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string ConnectAsUserButtonText {
            get {
                return ResourceManager.GetString("ConnectAsUserButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string ConnectInputLabel {
            get {
                return ResourceManager.GetString("ConnectInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej: pepe.
        /// </summary>
        public static string ConnectInputPlaceHolder {
            get {
                return ResourceManager.GetString("ConnectInputPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection lost due to error {0}. Reconnecting..
        /// </summary>
        public static string ConnectionLost {
            get {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ConnectPageTitle {
            get {
                return ResourceManager.GetString("ConnectPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for and admin to assist you..
        /// </summary>
        public static string InitialMessageTest {
            get {
                return ResourceManager.GetString("InitialMessageTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must enter a valid user name..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not message..
        /// </summary>
        public static string NotMessagesAvailable {
            get {
                return ResourceManager.GetString("NotMessagesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not users are available..
        /// </summary>
        public static string NotUserAvailable {
            get {
                return ResourceManager.GetString("NotUserAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wwwroot/media/audios.
        /// </summary>
        public static string SubDirectory {
            get {
                return ResourceManager.GetString("SubDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcribing audio....
        /// </summary>
        public static string TranscribingAudio {
            get {
                return ResourceManager.GetString("TranscribingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get connected users..
        /// </summary>
        public static string UnableToGetConnectedUsers {
            get {
                return ResourceManager.GetString("UnableToGetConnectedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get requested messages..
        /// </summary>
        public static string UnableToGetMessages {
            get {
                return ResourceManager.GetString("UnableToGetMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send the message to the selected user..
        /// </summary>
        public static string UnableToSendTheMessage {
            get {
                return ResourceManager.GetString("UnableToSendTheMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to transcript this audio..
        /// </summary>
        public static string UnableToTranscriptAudio {
            get {
                return ResourceManager.GetString("UnableToTranscriptAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user is already connected..
        /// </summary>
        public static string UserIsConnected {
            get {
                return ResourceManager.GetString("UserIsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect with this user..
        /// </summary>
        public static string UserIsDisconnected {
            get {
                return ResourceManager.GetString("UserIsDisconnected", resourceCulture);
            }
        }
    }
}
