// <auto-generated />
namespace Hospital_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AgainAddScheduleInDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AgainAddScheduleInDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201811240749139_AgainAddScheduleInDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
