create Table educational_details_be
	(edu_id int primary key not null,
	std_id 	int references student_data id not null,
	ssc_school	varchar() not null,
	ssc_year	varchar() not null,
	ssc_percentage	varchar() not null,
	ssc_class 	varchar() not null,
	hsc_school	varchar() not null,
	hsc_year	varchar() not null,
	hsc_pcm		varchar() not null,
	hsc_percentage	varchar() not null,
	hsc_class	varchar() not null,
	roll_no		varchar() not null,
	physics		int not null,
	chemistry	int not null,
	maths		int not null,
	total		int not null,
	jee_main_rank	int not null,
	contact_01	varchar() not null,
	contact_02	varchar() not null,
	acpc_no		varchar() not null,
	acpc_merit	varchar() not null,
	p1		varchar() not null,
	p2		varchar() not null,
	p3		varchar() not null,
	p4		varchar() not null
	);
