//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGC_MVC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGC_MVC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Legal Base Document.
        /// </summary>
        public static string BL_Title {
            get {
                return ResourceManager.GetString("BL_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string FieldType {
            get {
                return ResourceManager.GetString("FieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Field.
        /// </summary>
        public static string FieldType_Comment {
            get {
                return ResourceManager.GetString("FieldType_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Field (YYYY/MM/DD).
        /// </summary>
        public static string FieldType_Date {
            get {
                return ResourceManager.GetString("FieldType_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown List.
        /// </summary>
        public static string FieldType_DropdownList {
            get {
                return ResourceManager.GetString("FieldType_DropdownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Field.
        /// </summary>
        public static string FieldType_Email {
            get {
                return ResourceManager.GetString("FieldType_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiselect List.
        /// </summary>
        public static string FieldType_MultiselectList {
            get {
                return ResourceManager.GetString("FieldType_MultiselectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric Field.
        /// </summary>
        public static string FieldType_Numeric {
            get {
                return ResourceManager.GetString("FieldType_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiobutton List.
        /// </summary>
        public static string FieldType_RadiobuttonList {
            get {
                return ResourceManager.GetString("FieldType_RadiobuttonList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Text Field.
        /// </summary>
        public static string FieldType_SimpleText {
            get {
                return ResourceManager.GetString("FieldType_SimpleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. de Orden.
        /// </summary>
        public static string NoOrder {
            get {
                return ResourceManager.GetString("NoOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be and integer value.
        /// </summary>
        public static string NoOrderErrMessage {
            get {
                return ResourceManager.GetString("NoOrderErrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip.
        /// </summary>
        public static string Tooltip {
            get {
                return ResourceManager.GetString("Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Mesage.
        /// </summary>
        public static string ValidationMessage {
            get {
                return ResourceManager.GetString("ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name (Variable).
        /// </summary>
        public static string VariableShorcut {
            get {
                return ResourceManager.GetString("VariableShorcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
