//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsDataCore.Mods.Seg
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCIONES_PADRE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPCIONES_PADRE()
        {
            this.OPCIONES = new HashSet<OPCIONES>();
        }
    
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public string LINK { get; set; }
        public Nullable<int> ORDEN { get; set; }
        public bool ESTATUS { get; set; }
        public int OPCIONESTIPO { get; set; }
        public string CLASS { get; set; }
        public string ICON { get; set; }
        public Nullable<int> COD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPCIONES> OPCIONES { get; set; }
    }
}
