//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsDataCore.Mods.Pos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARGOS
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<double> VALOR { get; set; }
        public Nullable<int> AUTORID { get; set; }
    }
}
