//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsDataCore.Mods.Pos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIOS_ENTRADAS
    {
        public int ID { get; set; }
        public int PRODUCTOID { get; set; }
        public int STOCK_NEW { get; set; }
        public int STOCK_OLD { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<decimal> PRECIO2 { get; set; }
        public Nullable<decimal> PRECIO3 { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> ESTATUSID { get; set; }
    
        public virtual SERVICIOS SERVICIOS { get; set; }
    }
}
