//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsDataCore.Mods.Pos
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPANIA()
        {
            this.COMPANIA_SUCURSALES = new HashSet<COMPANIA_SUCURSALES>();
        }
    
        public int ID { get; set; }
        public string RNC { get; set; }
        public string NOMBRE { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string FAX { get; set; }
        public string CORREO1 { get; set; }
        public string CORREO2 { get; set; }
        public Nullable<int> SUBBARRIOID { get; set; }
        public string DIRECCION { get; set; }
        public string CODIGOPOSTAL { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public Nullable<int> AUTORID { get; set; }
        public Nullable<int> EMPRESAS_TIPOID { get; set; }
        public string CODIGO { get; set; }
    
        public virtual EMPRESAS_TIPO EMPRESAS_TIPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPANIA_SUCURSALES> COMPANIA_SUCURSALES { get; set; }
    }
}
