//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsDataCore.Mods.Pos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUENTAS()
        {
            this.CUENTAS_EVENTOS_DETALLE = new HashSet<CUENTAS_EVENTOS_DETALLE>();
            this.TRANSACCIONES_TIPO = new HashSet<TRANSACCIONES_TIPO>();
        }
    
        public int ID { get; set; }
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> BALACT { get; set; }
        public Nullable<System.DateTime> FECULTTRANS { get; set; }
        public Nullable<int> CUENTAS_CLASIFICACIONID { get; set; }
        public Nullable<int> AUTORID { get; set; }
    
        public virtual CUENTAS_CLASIFICACION CUENTAS_CLASIFICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUENTAS_EVENTOS_DETALLE> CUENTAS_EVENTOS_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACCIONES_TIPO> TRANSACCIONES_TIPO { get; set; }
    }
}
