//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsDataCore.Mods.Pos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICIOS()
        {
            this.SERVICIOS_ENTRADAS = new HashSet<SERVICIOS_ENTRADAS>();
            this.SERVICIOS_EQUIVALENCIAS = new HashSet<SERVICIOS_EQUIVALENCIAS>();
            this.SERVICIOS_UNIDADES = new HashSet<SERVICIOS_UNIDADES>();
            this.VENTAS_DETALLE = new HashSet<VENTAS_DETALLE>();
        }
    
        public int ID { get; set; }
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public string NOTAS { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public Nullable<int> STOCK { get; set; }
        public Nullable<int> CATEGORIAID { get; set; }
        public Nullable<int> AUTORID { get; set; }
        public string IMAGEN { get; set; }
        public Nullable<int> SUCURSALID { get; set; }
        public string BARCODE { get; set; }
        public Nullable<decimal> PRECIO2 { get; set; }
        public Nullable<decimal> PRECIO3 { get; set; }
    
        public virtual COMPANIA_SUCURSALES COMPANIA_SUCURSALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIOS_ENTRADAS> SERVICIOS_ENTRADAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIOS_EQUIVALENCIAS> SERVICIOS_EQUIVALENCIAS { get; set; }
        public virtual SERVICIOS_CATEGORIA SERVICIOS_CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIOS_UNIDADES> SERVICIOS_UNIDADES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTAS_DETALLE> VENTAS_DETALLE { get; set; }
    }
}
