//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsDataCore.Mods.Pos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIOS_UNIDADES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICIOS_UNIDADES()
        {
            this.SERVICIOS_EQUIVALENCIAS = new HashSet<SERVICIOS_EQUIVALENCIAS>();
            this.SERVICIOS_EQUIVALENCIAS1 = new HashSet<SERVICIOS_EQUIVALENCIAS>();
        }
    
        public int ID { get; set; }
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> SERVICIOID { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public Nullable<int> STOCK { get; set; }
    
        public virtual SERVICIOS SERVICIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIOS_EQUIVALENCIAS> SERVICIOS_EQUIVALENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIOS_EQUIVALENCIAS> SERVICIOS_EQUIVALENCIAS1 { get; set; }
    }
}
