//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsDataCore.Mods.Pos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENTAS()
        {
            this.VENTAS_DETALLE = new HashSet<VENTAS_DETALLE>();
        }
    
        public int ID { get; set; }
        public string NUMDOC { get; set; }
        public int TIPODOC { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<System.DateTime> FECHAPAGADA { get; set; }
        public Nullable<System.DateTime> FECHAABONO { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> BALANCEPENDIENTE { get; set; }
        public Nullable<decimal> SALDOPAGADO { get; set; }
        public Nullable<int> CLIENTEID { get; set; }
        public string COMENTARIOS { get; set; }
        public Nullable<int> ESTATUSID { get; set; }
        public Nullable<int> AUTORID { get; set; }
        public Nullable<decimal> CARGOS { get; set; }
        public Nullable<decimal> DESCUENTOS { get; set; }
        public Nullable<int> USERID { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTAS_DETALLE> VENTAS_DETALLE { get; set; }
    }
}
