// <auto-generated />
using Cabanas.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cabanas.API.Migrations
{
    [DbContext(typeof(CabanasContext))]
    [Migration("20190201195200_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cabanas.API.Models.Cabana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Cabanas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Aut. San Isidro",
                            Latitude = 18.4895593,
                            Longitude = -69.824781900000005,
                            Name = "Oriental"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Aut. San Isidro",
                            Latitude = 18.489203100000001,
                            Longitude = -69.824170100000003,
                            Name = "Alli"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Aut. San Isidro",
                            Latitude = 18.487943999999999,
                            Longitude = -69.822770000000006,
                            Name = "Aki"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Aut. San Isidro",
                            Latitude = 18.490191100000001,
                            Longitude = -69.822606399999998,
                            Name = "Cabañas Presidente"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Aut. San Isidro",
                            Latitude = 18.4897408,
                            Longitude = -69.822398800000002,
                            Name = "Extasis"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Aut. San Isidro",
                            Latitude = 18.4897809,
                            Longitude = -69.822173199999995,
                            Name = "Cariño"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Aut. San Isidro",
                            Latitude = 18.489488699999999,
                            Longitude = -69.8209564,
                            Name = "La compañia"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Aut. San Isidro",
                            Latitude = 18.489893800000001,
                            Longitude = -69.820286199999998,
                            Name = "yeah"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Aut. San Isidro",
                            Latitude = 18.490419800000002,
                            Longitude = -69.819985000000003,
                            Name = "Happy City"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Aut. San Isidro",
                            Latitude = 18.489663700000001,
                            Longitude = -69.819548900000001,
                            Name = "El jardin"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Aut. San Isidro",
                            Latitude = 18.490367500000001,
                            Longitude = -69.818503800000002,
                            Name = "Universal"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Aut. San Isidro",
                            Latitude = 18.4903327,
                            Longitude = -69.817480000000003,
                            Name = "Obssetion"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Aut. San Isidro",
                            Latitude = 18.490558100000001,
                            Longitude = -69.817541700000007,
                            Name = "Ta jevy"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Aut. San Isidro",
                            Latitude = 18.491107800000002,
                            Longitude = -69.822627400000002,
                            Name = "Miami"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Aut. San Isidro",
                            Latitude = 18.490600199999999,
                            Longitude = -69.822997599999994,
                            Name = "Scape"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Aut. San Isidro",
                            Latitude = 18.490784999999999,
                            Longitude = -69.823844100000002,
                            Name = "Cabañas del Caribe"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Ave. Los Beisbolistas  Manoguayabo",
                            Latitude = 18.448696699999999,
                            Longitude = -69.981779299999999,
                            Name = "Nuevo mundo"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Ave. Los Beisbolistas  Manoguayabo",
                            Latitude = 18.484442699999999,
                            Longitude = -69.984988299999998,
                            Name = "Popular"
                        },
                        new
                        {
                            Id = 19,
                            Address = "Ave. Los Beisbolistas  Manoguayabo",
                            Latitude = 18.484038399999999,
                            Longitude = -69.984555900000004,
                            Name = "Nuevo milenio"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Ave. Los Beisbolistas  Manoguayabo",
                            Latitude = 18.483819700000002,
                            Longitude = -69.9797394,
                            Name = "Manhattan"
                        },
                        new
                        {
                            Id = 21,
                            Address = "Ave. Los Beisbolistas  Manoguayabo",
                            Latitude = 18.484345399999999,
                            Longitude = -69.978920200000005,
                            Name = "Ciudad de oro"
                        },
                        new
                        {
                            Id = 22,
                            Address = "Ave. Los Beisbolistas  Manoguayabo",
                            Latitude = 18.484638199999999,
                            Longitude = -69.978840399999996,
                            Name = "Motel florida"
                        },
                        new
                        {
                            Id = 23,
                            Address = "Ave. Los Beisbolistas  Manoguayabo",
                            Latitude = 18.484196600000001,
                            Longitude = -69.982178200000007,
                            Name = "Primavera"
                        },
                        new
                        {
                            Id = 24,
                            Address = "Aut. Duarte KM 11 y 1/2",
                            Latitude = 18.498299299999999,
                            Longitude = -69.991755499999996,
                            Name = "Ciudad corazón"
                        },
                        new
                        {
                            Id = 25,
                            Address = "Aut. Duarte KM 11 y 1/2",
                            Latitude = 18.498591600000001,
                            Longitude = -69.992406000000003,
                            Name = "Villa campo"
                        },
                        new
                        {
                            Id = 26,
                            Address = "Aut. 30 de Mayo  KM 12",
                            Latitude = 18.424459299999999,
                            Longitude = -69.989453100000006,
                            Name = "Bayamesa"
                        },
                        new
                        {
                            Id = 27,
                            Address = "Aut. 30 de Mayo  KM 12",
                            Latitude = 18.424518200000001,
                            Longitude = -69.989915499999995,
                            Name = "Mister"
                        },
                        new
                        {
                            Id = 28,
                            Address = "Aut. 30 de Mayo  KM 12",
                            Latitude = 18.424664400000001,
                            Longitude = -69.990071,
                            Name = "Love"
                        },
                        new
                        {
                            Id = 29,
                            Address = "Aut. 30 de Mayo  KM 12",
                            Latitude = 18.425150800000001,
                            Longitude = -69.990352099999996,
                            Name = "Costa azul"
                        },
                        new
                        {
                            Id = 30,
                            Address = "Aut. 30 de Mayo  KM 12",
                            Latitude = 18.426400000000001,
                            Longitude = -69.991174400000006,
                            Name = "Si o No"
                        },
                        new
                        {
                            Id = 31,
                            Address = "Aut. 30 de Mayo  KM 12",
                            Latitude = 18.425093,
                            Longitude = -69.992578300000005,
                            Name = "Yes"
                        },
                        new
                        {
                            Id = 32,
                            Address = "Aut. 30 de Mayo  KM 12",
                            Latitude = 18.425558899999999,
                            Longitude = -69.9937288,
                            Name = "Kiss"
                        },
                        new
                        {
                            Id = 33,
                            Address = "Aut. 30 de Mayo  KM 12",
                            Latitude = 18.424954400000001,
                            Longitude = -69.993766800000003,
                            Name = "La uni"
                        },
                        new
                        {
                            Id = 34,
                            Address = "Aut. 30 de Mayo  KM 12",
                            Latitude = 18.424263,
                            Longitude = -69.992290199999999,
                            Name = "Tia Tania"
                        },
                        new
                        {
                            Id = 35,
                            Address = "Aut. 30 de Mayo  KM 12",
                            Latitude = 18.424177199999999,
                            Longitude = -69.991686400000006,
                            Name = "Honey moon"
                        },
                        new
                        {
                            Id = 36,
                            Address = "Aut. 30 de Mayo  KM 12",
                            Latitude = 18.423432699999999,
                            Longitude = -69.990826400000003,
                            Name = "Chevere"
                        },
                        new
                        {
                            Id = 37,
                            Address = "Aut. 30 de Mayo  KM 12",
                            Latitude = 18.423709800000001,
                            Longitude = -69.990465900000004,
                            Name = "Okey"
                        },
                        new
                        {
                            Id = 38,
                            Address = "Calle Juan A Vicioso  Sto Dgo",
                            Latitude = 18.4281617,
                            Longitude = -69.968924400000006,
                            Name = "Queen"
                        },
                        new
                        {
                            Id = 39,
                            Address = "Calle 32 Felix Evaristo Mejia",
                            Latitude = 18.4945129,
                            Longitude = -69.909946399999995,
                            Name = "Cabañas el Príncipe"
                        },
                        new
                        {
                            Id = 40,
                            Address = "Ave. Pedro Livio Cedeño",
                            Latitude = 18.496143499999999,
                            Longitude = -69.913885300000004,
                            Name = "Cabañas La Playa"
                        },
                        new
                        {
                            Id = 41,
                            Address = "Aut. San Isidro",
                            Latitude = 18.4901968,
                            Longitude = -69.821542399999998,
                            Name = "La Oficina"
                        },
                        new
                        {
                            Id = 42,
                            Address = "Calle Americo Lugo",
                            Latitude = 18.490216700000001,
                            Longitude = -69.915892900000003,
                            Name = "Hotel Fiesta"
                        },
                        new
                        {
                            Id = 43,
                            Address = "Calle Mauricio Baez",
                            Latitude = 18.488173700000001,
                            Longitude = -69.915096899999995,
                            Name = "Hotel cabañas Isla de Oro"
                        },
                        new
                        {
                            Id = 44,
                            Address = "Ave. Nicolas de Ovando",
                            Latitude = 18.500178099999999,
                            Longitude = -69.910271100000003,
                            Name = "Hotel cabañas Sol de Verano"
                        },
                        new
                        {
                            Id = 45,
                            Address = "Ave. Nicolas de Ovando",
                            Latitude = 18.500156700000002,
                            Longitude = -69.911650899999998,
                            Name = "Hotel cabañas Lincoln"
                        },
                        new
                        {
                            Id = 46,
                            Address = "Calle 28 Anibal de Espinosa",
                            Latitude = 18.496359999999999,
                            Longitude = -69.909606600000004,
                            Name = "Cabaña Hotel Latino"
                        },
                        new
                        {
                            Id = 47,
                            Address = "Calle 28 Anibal de Espinosa",
                            Latitude = 18.489732199999999,
                            Longitude = -69.917253299999999,
                            Name = "Cabañas Hotel 8"
                        },
                        new
                        {
                            Id = 48,
                            Address = "Ensanche la Fe",
                            Latitude = 18.497231500000002,
                            Longitude = -69.921933100000004,
                            Name = "Cabañas el mundo del Amor"
                        },
                        new
                        {
                            Id = 49,
                            Address = "Calle San Juan de la Maguana",
                            Latitude = 18.5017274,
                            Longitude = -69.912822899999995,
                            Name = "Cabañas Hotel Internacional"
                        },
                        new
                        {
                            Id = 50,
                            Address = "Av. Hermanas Mirabal  Villa Mella",
                            Latitude = 18.527448799999998,
                            Longitude = -69.915571999999997,
                            Name = "Cabañas el Bonche"
                        },
                        new
                        {
                            Id = 51,
                            Address = "Calle Ramon Matias Mella  Villa Mella",
                            Latitude = 18.550612900000001,
                            Longitude = -69.900295900000003,
                            Name = "Cabañas Monte Bonito"
                        },
                        new
                        {
                            Id = 52,
                            Address = "Ave. Charles de Gaulle  Villa Mella",
                            Latitude = 18.545226599999999,
                            Longitude = -69.897776399999998,
                            Name = "Cabañas hotel Super"
                        },
                        new
                        {
                            Id = 53,
                            Address = "Ave. Charles de Gaulle  Villa Mella",
                            Latitude = 18.5472231,
                            Longitude = -69.890065699999994,
                            Name = "Cabañas Horny"
                        },
                        new
                        {
                            Id = 54,
                            Address = "Ave. Charles de Gaulle  Sabana Perdida",
                            Latitude = 18.540917799999999,
                            Longitude = -69.855176599999993,
                            Name = "Cabañas Hoy"
                        },
                        new
                        {
                            Id = 55,
                            Address = "Ave. Charles de Gaulle  Sabana Perdida",
                            Latitude = 18.541952299999998,
                            Longitude = -69.856220899999997,
                            Name = "Cabañas Preciosa"
                        },
                        new
                        {
                            Id = 56,
                            Address = "Ave. Charles de Gaulle  Zona Horiental",
                            Latitude = 18.535277099999998,
                            Longitude = -69.847774599999994,
                            Name = "Cabañas la Paz"
                        },
                        new
                        {
                            Id = 57,
                            Address = "Marginal de las Americas",
                            Latitude = 18.4670822,
                            Longitude = -69.820685900000001,
                            Name = "Cabañas Miramar"
                        },
                        new
                        {
                            Id = 58,
                            Address = "Marginal de las Americas",
                            Latitude = 18.466696899999999,
                            Longitude = -69.793395899999993,
                            Name = "Cabañas Son"
                        },
                        new
                        {
                            Id = 59,
                            Address = "Ave. 27 de Febrero  Santo Domingo",
                            Latitude = 18.4508808,
                            Longitude = -69.963961900000001,
                            Name = "Cabañas Centrun"
                        },
                        new
                        {
                            Id = 60,
                            Address = "Ave. Isabel Aguiar  Sto Dgo.",
                            Latitude = 18.468564000000001,
                            Longitude = -69.973697000000001,
                            Name = "Cabañas Ahora"
                        },
                        new
                        {
                            Id = 61,
                            Address = "Ave. Isabel Aguiar  Santo Domingo",
                            Latitude = 18.471416699999999,
                            Longitude = -69.972385000000003,
                            Name = "Cabañas Hotel Roma"
                        },
                        new
                        {
                            Id = 62,
                            Address = "Ave. Isabel Aguiar  Santo Domingo",
                            Latitude = 18.4733415,
                            Longitude = -69.971580399999993,
                            Name = "Hotel Cabañas Mi Cam Cam"
                        },
                        new
                        {
                            Id = 63,
                            Address = " Aut. Duarte  Santiago De Los Caballeros",
                            Latitude = 19.4247288,
                            Longitude = -70.6478927,
                            Name = "Cabañas Turistica Eclipse"
                        },
                        new
                        {
                            Id = 64,
                            Address = "Aut. Duarte  Santiago De Los Caballeros",
                            Latitude = 19.4202428,
                            Longitude = -70.648786700000002,
                            Name = "Bora Bora Aparta Hotel"
                        },
                        new
                        {
                            Id = 65,
                            Address = "Santiago De Los Caballeros",
                            Latitude = 19.415979,
                            Longitude = -70.646714599999996,
                            Name = "Cabañas Venus"
                        },
                        new
                        {
                            Id = 66,
                            Address = "Santiago De Los Caballeros",
                            Latitude = 19.4200141,
                            Longitude = -70.648353099999994,
                            Name = "Helios Aparta Hotel"
                        },
                        new
                        {
                            Id = 67,
                            Address = "Santiago De Los Caballeros",
                            Latitude = 19.411484699999999,
                            Longitude = -70.639889699999998,
                            Name = "Cabañas Turisticas Ethics"
                        },
                        new
                        {
                            Id = 68,
                            Address = "Carretera Las Palomas  Santiago De Los Caballeros",
                            Latitude = 19.426135200000001,
                            Longitude = -70.648783899999998,
                            Name = "Moteles El Arco"
                        },
                        new
                        {
                            Id = 69,
                            Address = "Carretera Sabaneta  Las Palomas ",
                            Latitude = 19.426135200000001,
                            Longitude = -70.651370400000005,
                            Name = "Horus Aparta Hotel"
                        },
                        new
                        {
                            Id = 70,
                            Address = "Santiago De Los Caballeros",
                            Latitude = 19.443836600000001,
                            Longitude = -70.667987999999994,
                            Name = "Cabañas Villas del Sol"
                        },
                        new
                        {
                            Id = 71,
                            Address = " Carretera Las Palomas  Santiago ",
                            Latitude = 19.425567099999999,
                            Longitude = -70.651206200000004,
                            Name = "Cabañas Imperial"
                        },
                        new
                        {
                            Id = 72,
                            Address = "Santiago De Los Caballeros",
                            Latitude = 19.4197816,
                            Longitude = -70.6512666,
                            Name = "Moteles el Palmar"
                        },
                        new
                        {
                            Id = 73,
                            Address = " Santiago De Los Caballeros",
                            Latitude = 19.445165299999999,
                            Longitude = -70.667007600000005,
                            Name = "Moteles Venus "
                        },
                        new
                        {
                            Id = 74,
                            Address = "Santiago De Los Caballeros",
                            Latitude = 19.450054000000002,
                            Longitude = -70.665332800000002,
                            Name = "Cabañas aparta Hotel Pegasus"
                        },
                        new
                        {
                            Id = 75,
                            Address = "Santiago De Los Caballeros",
                            Latitude = 19.449765200000002,
                            Longitude = -70.665608500000005,
                            Name = "Cabañas Turísticas Afrodita"
                        },
                        new
                        {
                            Id = 76,
                            Address = "Santiago De Los Caballeros",
                            Latitude = 19.500501,
                            Longitude = -70.741505399999994,
                            Name = "Cabañas Elysium"
                        },
                        new
                        {
                            Id = 77,
                            Address = "Aut. Las Americas ",
                            Latitude = 18.4855704,
                            Longitude = -69.867223300000006,
                            Name = "Hotel Cabañas Reunion"
                        },
                        new
                        {
                            Id = 78,
                            Address = "Ave. San Vincente de Paul",
                            Latitude = 18.510334499999999,
                            Longitude = -69.874488099999994,
                            Name = "Cabañas Hotel La Cita"
                        },
                        new
                        {
                            Id = 79,
                            Address = "Ave. San Vicente de Paul",
                            Latitude = 18.4943937,
                            Longitude = -69.851396300000005,
                            Name = "Cabañas Diamante Azul"
                        },
                        new
                        {
                            Id = 80,
                            Address = "Ave. San Vicente de Paul",
                            Latitude = 18.4962871,
                            Longitude = -69.851527099999998,
                            Name = "Cabañas Hotel El Crucero"
                        },
                        new
                        {
                            Id = 81,
                            Address = "La Vega",
                            Latitude = 19.2417488,
                            Longitude = -70.525228400000003,
                            Name = "Cabañas aparta hotel Galaxy"
                        },
                        new
                        {
                            Id = 82,
                            Address = "Aut. Duarte  La Vega",
                            Latitude = 19.2539646,
                            Longitude = -70.562802899999994,
                            Name = "Cabañas Turísticas La Vega Real"
                        },
                        new
                        {
                            Id = 83,
                            Address = "Aut. Duarte  La Vega",
                            Latitude = 19.2750618,
                            Longitude = -70.570166900000004,
                            Name = "Cabañas Paraiso"
                        },
                        new
                        {
                            Id = 84,
                            Address = "Aut. Duarte  La Vega",
                            Latitude = 19.317617899999998,
                            Longitude = -70.586611700000006,
                            Name = "Cabañas Jupiter"
                        },
                        new
                        {
                            Id = 85,
                            Address = "La Vega",
                            Latitude = 19.363647700000001,
                            Longitude = -70.603590499999996,
                            Name = "Cabañas Villa Bella"
                        },
                        new
                        {
                            Id = 86,
                            Address = "Aut. Duarte  La Vega",
                            Latitude = 19.218302999999999,
                            Longitude = -70.496960700000002,
                            Name = "Cabañas Turísticas Atlas"
                        },
                        new
                        {
                            Id = 87,
                            Address = "Aut. Duarte  Bonao",
                            Latitude = 18.932262999999999,
                            Longitude = -70.387951999999999,
                            Name = "Cabañas las Palmas"
                        },
                        new
                        {
                            Id = 88,
                            Address = "Aut. Duarte  Bonao",
                            Latitude = 18.932125500000001,
                            Longitude = -70.386364299999997,
                            Name = "Cabañas La Fuente del Placer"
                        },
                        new
                        {
                            Id = 89,
                            Address = "Aut. Duarte  Piedra Blanca",
                            Latitude = 18.8575911,
                            Longitude = -70.342830399999997,
                            Name = "Cabañas Heaven"
                        },
                        new
                        {
                            Id = 90,
                            Address = "Aut. Joaquin Balaguer  Santiago",
                            Latitude = 19.502274400000001,
                            Longitude = -70.746448200000003,
                            Name = "Cabañas aparta hotel Ibiza"
                        },
                        new
                        {
                            Id = 91,
                            Address = "Santiago De Los Caballeros",
                            Latitude = 19.5036901,
                            Longitude = -70.746107699999996,
                            Name = "Cabañas Turísticas Blue Castle"
                        },
                        new
                        {
                            Id = 92,
                            Address = "Santiago De Los Caballeros",
                            Latitude = 19.416379899999999,
                            Longitude = -70.639911600000005,
                            Name = "Cabañas Zeus"
                        },
                        new
                        {
                            Id = 93,
                            Address = "Santiago De Los Caballeros",
                            Latitude = 19.505016399999999,
                            Longitude = -70.745878300000001,
                            Name = "Cabañas Poseidon"
                        },
                        new
                        {
                            Id = 94,
                            Address = "Santiago De Los Caballeros",
                            Latitude = 19.5067892,
                            Longitude = -70.745694400000005,
                            Name = "Cabañas Venus VIP"
                        },
                        new
                        {
                            Id = 95,
                            Address = "Circunvalacion Norte  Villa Gonzalez  Santiago ",
                            Latitude = 19.5195331,
                            Longitude = -70.762640399999995,
                            Name = "Cabañas Mirage"
                        },
                        new
                        {
                            Id = 96,
                            Address = "Higuey La Otra Banda  km 1.5",
                            Latitude = 18.644299400000001,
                            Longitude = -68.695265300000003,
                            Name = "Cabañas Copa Caribe"
                        },
                        new
                        {
                            Id = 97,
                            Address = "Ave. San Martín No.198  Ens. La Fé",
                            Latitude = 18.4845778662322,
                            Longitude = -69.915845207870007,
                            Name = "Hotel Restaurant Londres"
                        },
                        new
                        {
                            Id = 98,
                            Address = "Ave. de las Hortensias",
                            Latitude = 18.952211533885102,
                            Longitude = -70.402122996747394,
                            Name = "Bonao Inn"
                        },
                        new
                        {
                            Id = 99,
                            Address = "Ave. de las Hortensias",
                            Latitude = 18.944216598557901,
                            Longitude = -70.397710762917896,
                            Name = "Hermes Aparta Hotel"
                        },
                        new
                        {
                            Id = 100,
                            Address = "Av. Jose Contreras",
                            Latitude = 18.460311999999998,
                            Longitude = -69.923944000000006,
                            Name = "Hotel José Contreras"
                        },
                        new
                        {
                            Id = 101,
                            Address = "Aut. San Isidro",
                            Latitude = 18.489675946200201,
                            Longitude = -69.823696576058794,
                            Name = "Malibu"
                        },
                        new
                        {
                            Id = 102,
                            Address = "La Vega",
                            Latitude = 19.203004756713799,
                            Longitude = -70.494820140302096,
                            Name = "Aparta Hotel Los Pinos"
                        },
                        new
                        {
                            Id = 103,
                            Address = "Av. Presidente Antonio Guzman F.",
                            Latitude = 19.440600817660599,
                            Longitude = -70.724938586354199,
                            Name = "View Aparta Hotel"
                        },
                        new
                        {
                            Id = 104,
                            Address = "Aut. 6 de Noviembre",
                            Latitude = 18.40457,
                            Longitude = -70.137540000000001,
                            Name = "Cabañas Cupido"
                        },
                        new
                        {
                            Id = 105,
                            Address = "",
                            Latitude = 18.464224736381201,
                            Longitude = -69.895942211151095,
                            Name = "Hotel Maison Gautreaux"
                        },
                        new
                        {
                            Id = 106,
                            Address = "",
                            Latitude = 19.306000000000001,
                            Longitude = -69.562780000000004,
                            Name = "Residencia Hotel Madrugada"
                        },
                        new
                        {
                            Id = 107,
                            Address = "Calle Arzobispo Nouel #402",
                            Latitude = 18.470904000000001,
                            Longitude = -69.891121999999996,
                            Name = "Hotel Discovery"
                        },
                        new
                        {
                            Id = 108,
                            Address = "Ave. Independencia No. 304  Gazcue",
                            Latitude = 18.465494,
                            Longitude = -69.896879999999996,
                            Name = "Hotel Duque de Wellington"
                        },
                        new
                        {
                            Id = 109,
                            Address = "Calle Danae #35  Gazcue",
                            Latitude = 18.468426999999998,
                            Longitude = -69.897639999999996,
                            Name = " Hotel Riparbella"
                        },
                        new
                        {
                            Id = 110,
                            Address = "Av Doctor Fernando Arturo Defilló # 43",
                            Latitude = 18.457052000000001,
                            Longitude = -69.947284999999994,
                            Name = "Hotel Bella Vista"
                        },
                        new
                        {
                            Id = 111,
                            Address = "Abraham Lincoln #116",
                            Latitude = 18.455646999999999,
                            Longitude = -69.924854999999994,
                            Name = " Hotel Royal Palace"
                        },
                        new
                        {
                            Id = 112,
                            Address = "Calle Dr. Heriberto Pieter No.34  Ensanche Naco",
                            Latitude = 18.481586,
                            Longitude = -69.927802,
                            Name = "Hotel Aladino"
                        },
                        new
                        {
                            Id = 113,
                            Address = "Av. Independencia #45  Gazcue",
                            Latitude = 18.468387,
                            Longitude = -69.894406000000004,
                            Name = "Hotel-Residence Venezia"
                        },
                        new
                        {
                            Id = 114,
                            Address = "Calle La Danae No. 18  Gazcue",
                            Latitude = 18.467873000000001,
                            Longitude = -69.897242000000006,
                            Name = "Hotel La Danae"
                        },
                        new
                        {
                            Id = 115,
                            Address = "Calle Arzobispo Meriño #111",
                            Latitude = 18.473769999999998,
                            Longitude = -69.884462999999997,
                            Name = "Hotel Conde de Peñalba"
                        },
                        new
                        {
                            Id = 116,
                            Address = "Calle Duarte 106  Ciudad Colonial",
                            Latitude = 18.473738999999998,
                            Longitude = -69.886275999999995,
                            Name = " Boutique Hotel Palacio"
                        },
                        new
                        {
                            Id = 117,
                            Address = "Arismendy Valenzuela 2",
                            Latitude = 18.451426000000001,
                            Longitude = -69.607816,
                            Name = "Hotel Mango"
                        },
                        new
                        {
                            Id = 118,
                            Address = "Calle Abraham Nuñez #27",
                            Latitude = 18.447241999999999,
                            Longitude = -69.608624000000006,
                            Name = "Hotel Zapata"
                        },
                        new
                        {
                            Id = 119,
                            Address = "Calle Duarte #17",
                            Latitude = 18.448513999999999,
                            Longitude = -69.599418999999997,
                            Name = "Hotel Neptuno"
                        },
                        new
                        {
                            Id = 120,
                            Address = "Calle San Rafael  # 18",
                            Latitude = 18.448331,
                            Longitude = -69.613347000000005,
                            Name = "Apart-Hotel Parco Del Caribe"
                        },
                        new
                        {
                            Id = 121,
                            Address = "Calle 20 de Diciembre #5",
                            Latitude = 18.44952,
                            Longitude = -69.606769999999997,
                            Name = "Hotel El Gaucho"
                        },
                        new
                        {
                            Id = 122,
                            Address = "Calle Dominguez  #8",
                            Latitude = 18.448058,
                            Longitude = -69.608275000000006,
                            Name = "Hotel Casa Coco"
                        },
                        new
                        {
                            Id = 123,
                            Address = "Calle Don Antonio Guzman No. 3",
                            Latitude = 19.230879928865701,
                            Longitude = -70.530410371720706,
                            Name = "Hotel el Rey"
                        },
                        new
                        {
                            Id = 124,
                            Address = "Aut. Duarte",
                            Latitude = 18.967600300000001,
                            Longitude = -70.413584099999994,
                            Name = "Hotel Jacaranda"
                        },
                        new
                        {
                            Id = 125,
                            Address = "Cesar Nicolas Penson Gazcue",
                            Latitude = 18.472451629773399,
                            Longitude = -69.897692017257199,
                            Name = "Carey House Hotel"
                        },
                        new
                        {
                            Id = 126,
                            Address = "Las Terrenas",
                            Latitude = 19.306939395355201,
                            Longitude = -69.555738684120101,
                            Name = "Monaco Cottage"
                        },
                        new
                        {
                            Id = 127,
                            Address = "Los Tres Ojos",
                            Latitude = 18.482634000000001,
                            Longitude = -69.846737000000005,
                            Name = "Cabañas Villa España"
                        },
                        new
                        {
                            Id = 128,
                            Address = "Ave Juan Pablo Duarte",
                            Latitude = 18.494551938272,
                            Longitude = -69.900460056960497,
                            Name = "Hotel Cabañas Presidente"
                        },
                        new
                        {
                            Id = 129,
                            Address = "Calle Santa Barbara",
                            Latitude = 19.203859000000001,
                            Longitude = -69.332436000000001,
                            Name = "Casa de huespedes Mildania"
                        },
                        new
                        {
                            Id = 130,
                            Address = "Calle Duarte",
                            Latitude = 19.204855999999999,
                            Longitude = -69.333596,
                            Name = "DOCIA BLACKPAKERS"
                        },
                        new
                        {
                            Id = 131,
                            Address = "C/ Francisco del Rosario Sanchez",
                            Latitude = 19.203838000000001,
                            Longitude = -69.339260999999993,
                            Name = "Hotel Leidy"
                        },
                        new
                        {
                            Id = 132,
                            Address = "Ave Circunvalacion",
                            Latitude = 19.203814999999999,
                            Longitude = -69.338133999999997,
                            Name = "Hotel Cotubanama"
                        },
                        new
                        {
                            Id = 133,
                            Address = "Malecon San Pedro",
                            Latitude = 18.440550999999999,
                            Longitude = -69.309973999999997,
                            Name = " Hotel Escuela Macorix"
                        },
                        new
                        {
                            Id = 134,
                            Address = "Guayacanes",
                            Latitude = 18.418574,
                            Longitude = -69.458357000000007,
                            Name = "Apartamentos OASIS"
                        },
                        new
                        {
                            Id = 135,
                            Address = "Juan Dolio",
                            Latitude = 18.426687999999999,
                            Longitude = -69.416025000000005,
                            Name = "Hotel Fior Di Loto"
                        },
                        new
                        {
                            Id = 136,
                            Address = "Calle Central 79",
                            Latitude = 18.416132000000001,
                            Longitude = -69.469695999999999,
                            Name = "Pensión Lucirooms"
                        },
                        new
                        {
                            Id = 137,
                            Address = "Av. Padre Abreu Esq. Pedro A. Lluberes",
                            Latitude = 18.432724,
                            Longitude = -68.970692,
                            Name = "Hotel Olimpo"
                        },
                        new
                        {
                            Id = 138,
                            Address = "Carretera La Romana - Bayahibe Km 13",
                            Latitude = 18.438549999999999,
                            Longitude = -68.867802999999995,
                            Name = "Hotel Vecchia Caserma"
                        },
                        new
                        {
                            Id = 139,
                            Address = "Carretera Higüey - Yuma Km. 1",
                            Latitude = 18.592863999999999,
                            Longitude = -68.716960999999998,
                            Name = " K&C Gran Hotel"
                        },
                        new
                        {
                            Id = 140,
                            Address = "Carretera Higuey-Yuma",
                            Latitude = 18.431927000000002,
                            Longitude = -68.687400999999994,
                            Name = "Mi Tesoro"
                        },
                        new
                        {
                            Id = 141,
                            Address = "Calle Principal",
                            Latitude = 18.369828999999999,
                            Longitude = -68.839256000000006,
                            Name = "Hotel Bayahibe"
                        },
                        new
                        {
                            Id = 142,
                            Address = "Ave EE UU  C/Guarionex 3",
                            Latitude = 18.687815000000001,
                            Longitude = -68.454255000000003,
                            Name = " Guesthouse Las Piedras"
                        },
                        new
                        {
                            Id = 143,
                            Address = "Carretera Punta Cana a 300m",
                            Latitude = 18.604693000000001,
                            Longitude = -68.483042999999995,
                            Name = "Aparta Hotel Veron"
                        },
                        new
                        {
                            Id = 144,
                            Address = "Carretera de Veron-Punta Cana km 31",
                            Latitude = 18.597024999999999,
                            Longitude = -68.438193999999996,
                            Name = "Hotel Yonu"
                        },
                        new
                        {
                            Id = 145,
                            Address = "Carretera Higuey Punta Cana Km 31",
                            Latitude = 18.596540999999998,
                            Longitude = -68.444218000000006,
                            Name = "Hotel Restaurant El Bosque"
                        },
                        new
                        {
                            Id = 146,
                            Address = "Residencial Villas Bávaro  Avenida del Bosque",
                            Latitude = 18.667750000000002,
                            Longitude = -68.412332000000006,
                            Name = "Apartamentos Villa Elena"
                        },
                        new
                        {
                            Id = 147,
                            Address = "Avenida Italia",
                            Latitude = 18.692194000000001,
                            Longitude = -68.440276999999995,
                            Name = "Hotel Flamboyan"
                        },
                        new
                        {
                            Id = 148,
                            Address = "Los Corales",
                            Latitude = 18.684121999999999,
                            Longitude = -68.416499999999999,
                            Name = "Bavaro Hostel"
                        },
                        new
                        {
                            Id = 149,
                            Address = "Carretera Veron Km 36",
                            Latitude = 18.594697,
                            Longitude = -68.453390999999996,
                            Name = "Hotel El Viajante"
                        },
                        new
                        {
                            Id = 150,
                            Address = "Principe de Los Corales  14",
                            Latitude = 18.700220999999999,
                            Longitude = -68.449512999999996,
                            Name = "Hostel Punta Cana"
                        },
                        new
                        {
                            Id = 151,
                            Address = "Av. Alemania",
                            Latitude = 18.682006000000001,
                            Longitude = -68.413033999999996,
                            Name = "Apartamento Bavaro Punta Cana El Dorado"
                        },
                        new
                        {
                            Id = 152,
                            Address = "Carretera Verón Punta Cana Km 48",
                            Latitude = 18.58324,
                            Longitude = -68.398071000000002,
                            Name = " Hotel Plaza Coral"
                        },
                        new
                        {
                            Id = 153,
                            Address = "Las Terrenas",
                            Latitude = 19.321743999999999,
                            Longitude = -69.535893000000002,
                            Name = "Hotel Casa Robinson"
                        },
                        new
                        {
                            Id = 154,
                            Address = "Boca de Mao",
                            Latitude = 19.586743999999999,
                            Longitude = -71.033572000000007,
                            Name = "Cabañas Bernard"
                        },
                        new
                        {
                            Id = 155,
                            Address = "Boca de Mao",
                            Latitude = 19.585522000000001,
                            Longitude = -71.028559000000001,
                            Name = "Cabañas Monte Bello"
                        },
                        new
                        {
                            Id = 156,
                            Address = "Polo  Barahona",
                            Latitude = 18.115409220969301,
                            Longitude = -71.273741837921094,
                            Name = "El Rancho Lembert"
                        },
                        new
                        {
                            Id = 157,
                            Address = "San Juan ",
                            Latitude = 18.864709999999999,
                            Longitude = -71.367189999999994,
                            Name = "Hotel alegria"
                        },
                        new
                        {
                            Id = 158,
                            Address = "",
                            Latitude = 18.521148,
                            Longitude = -70.010689999999997,
                            Name = "Hotel El Encuentro"
                        },
                        new
                        {
                            Id = 159,
                            Address = "ave. Albert Thomas # 264",
                            Latitude = 18.504322582535799,
                            Longitude = -69.896680489182401,
                            Name = "Hotel Noche de Travesuras"
                        },
                        new
                        {
                            Id = 160,
                            Address = "",
                            Latitude = 18.256879000000001,
                            Longitude = -70.285514000000006,
                            Name = "Cabañas Tentacion"
                        },
                        new
                        {
                            Id = 161,
                            Address = "",
                            Latitude = 18.462511572155801,
                            Longitude = -69.975928030908094,
                            Name = "Hotel Cima"
                        },
                        new
                        {
                            Id = 162,
                            Address = "Dr A Martínez 1  Sosua",
                            Latitude = 19.766349999999999,
                            Longitude = -70.516530000000003,
                            Name = " Hotel Casa Marina Beach Resort"
                        },
                        new
                        {
                            Id = 163,
                            Address = "Carr Puerto Plata - Navarrete",
                            Latitude = 19.812034000000001,
                            Longitude = -70.730485000000002,
                            Name = "Aparta Hotel Sensación"
                        },
                        new
                        {
                            Id = 164,
                            Address = "Car Limonal Abajo Km 7 1/2",
                            Latitude = 19.417732000000001,
                            Longitude = -70.646879999999996,
                            Name = "Olympus Cabañas Turísticas"
                        },
                        new
                        {
                            Id = 165,
                            Address = "Car Romana - S Pedro Km 6",
                            Latitude = 18.444291,
                            Longitude = -69.041272000000006,
                            Name = "Cabañas Turísticas Tu y Yo"
                        },
                        new
                        {
                            Id = 166,
                            Address = " R Cáceres 1  Coroso",
                            Latitude = 19.386801999999999,
                            Longitude = -70.532399999999996,
                            Name = "Cabañas Turísticas Las Nubes"
                        },
                        new
                        {
                            Id = 167,
                            Address = "Car La Romana - Higuey ",
                            Latitude = 18.4241362,
                            Longitude = -68.946928900000003,
                            Name = "Casa de Campo Hotel"
                        },
                        new
                        {
                            Id = 168,
                            Address = "Car San Fco - Tenares 12",
                            Latitude = 19.325865,
                            Longitude = -70.278323,
                            Name = "Anubys Cabañas Turísticas"
                        },
                        new
                        {
                            Id = 169,
                            Address = "Aut 30 de Mayo 12",
                            Latitude = 18.443899999999999,
                            Longitude = -69.927099999999996,
                            Name = "Bellamar Hotel Y Restaurant"
                        },
                        new
                        {
                            Id = 170,
                            Address = "Car Padre Billini 1",
                            Latitude = 18.549613000000001,
                            Longitude = -70.501231000000004,
                            Name = "Cabaña Villa Ensueño"
                        },
                        new
                        {
                            Id = 171,
                            Address = "Aut 6 de Noviembre 1",
                            Latitude = 18.397106000000001,
                            Longitude = -70.144323,
                            Name = "Cabañas Cine"
                        },
                        new
                        {
                            Id = 172,
                            Address = "Aut 6 de Noviembre 1  San Cristóbal",
                            Latitude = 18.443180000000002,
                            Longitude = -69.965800000000002,
                            Name = "Cabañas Cine SD"
                        },
                        new
                        {
                            Id = 173,
                            Address = "Car Mella 1",
                            Latitude = 18.620284999999999,
                            Longitude = -68.726163999999997,
                            Name = "Cabañas Cristal"
                        },
                        new
                        {
                            Id = 174,
                            Address = "Av 6 de Noviembre 10",
                            Latitude = 18.430342,
                            Longitude = -70.099157000000005,
                            Name = "Cabañas De Amor"
                        },
                        new
                        {
                            Id = 175,
                            Address = "Car Guiza-Las Guaranas 1",
                            Latitude = 19.205321000000001,
                            Longitude = -70.220489999999998,
                            Name = "Cabañas Eros"
                        },
                        new
                        {
                            Id = 176,
                            Address = " Car Uvero Alto 1  Punta Cana ",
                            Latitude = 18.806797,
                            Longitude = -68.585114000000004,
                            Name = "Cabañas La Curva del Amor"
                        },
                        new
                        {
                            Id = 177,
                            Address = "",
                            Latitude = 18.424427999999999,
                            Longitude = -69.992958000000002,
                            Name = "Cabañas California"
                        },
                        new
                        {
                            Id = 178,
                            Address = "Av K Adenauer 11  Santo Domingo",
                            Latitude = 18.545435000000001,
                            Longitude = -69.900238999999999,
                            Name = "Cabañas Good"
                        },
                        new
                        {
                            Id = 179,
                            Address = "Carr Duarte 1  Cotui",
                            Latitude = 19.466660000000001,
                            Longitude = -70.69999,
                            Name = "Cabañas Holy Day"
                        },
                        new
                        {
                            Id = 180,
                            Address = "San Francisco de Macorís",
                            Latitude = 19.307600000000001,
                            Longitude = -70.281800000000004,
                            Name = "Cabañas La Macorisana"
                        },
                        new
                        {
                            Id = 181,
                            Address = "Carr Duarte Km 3  Santiago",
                            Latitude = 19.428108000000002,
                            Longitude = -70.654578000000001,
                            Name = "Cabañas Turisticas Sueños"
                        },
                        new
                        {
                            Id = 182,
                            Address = " Aut Stgo Navarrete  Santiago",
                            Latitude = 19.491102999999999,
                            Longitude = -70.725161,
                            Name = "Cabañas Villa Hermosa"
                        },
                        new
                        {
                            Id = 183,
                            Address = "Av E Unidos 5",
                            Latitude = 18.666169,
                            Longitude = -68.431177000000005,
                            Name = "Cabañas Vista Bávaro"
                        },
                        new
                        {
                            Id = 184,
                            Address = "Carr Guáranas Km 13 1/2",
                            Latitude = 19.261800000000001,
                            Longitude = -70.221599999999995,
                            Name = "Cañabas Perla"
                        },
                        new
                        {
                            Id = 185,
                            Address = "",
                            Latitude = 19.261780000000002,
                            Longitude = -70.219470000000001,
                            Name = "Cabañas Rebu"
                        },
                        new
                        {
                            Id = 186,
                            Address = "Carr San Fco-Tenares 12",
                            Latitude = 19.325167,
                            Longitude = -70.278486000000001,
                            Name = "Carolina High Aparta Hotel"
                        },
                        new
                        {
                            Id = 187,
                            Address = "Av Pdte A G Fernández 1",
                            Latitude = 19.287306999999998,
                            Longitude = -70.271214999999998,
                            Name = "Casa Dorada"
                        },
                        new
                        {
                            Id = 188,
                            Address = "Carr G las Guáranas 1",
                            Latitude = 19.214804000000001,
                            Longitude = -70.058183999999997,
                            Name = "Centro Turístico Girasoles"
                        },
                        new
                        {
                            Id = 189,
                            Address = "Carr F Basilis 20",
                            Latitude = 19.100667999999999,
                            Longitude = -70.654642999999993,
                            Name = "De La Montaña Cabañas Turísticas"
                        },
                        new
                        {
                            Id = 190,
                            Address = "Av Las Américas Km 10",
                            Latitude = 18.466047,
                            Longitude = -69.821235000000001,
                            Name = "Gran Bahamas Hotel & Cabañas"
                        },
                        new
                        {
                            Id = 191,
                            Address = "J I Reyes 65",
                            Latitude = 19.557929999999999,
                            Longitude = -71.077545999999998,
                            Name = "Hotel Cabaña San Roque"
                        },
                        new
                        {
                            Id = 192,
                            Address = "Carr Palenque 38",
                            Latitude = 18.288038,
                            Longitude = -70.124531000000005,
                            Name = "Cabañas Las Colinas Del Placer"
                        },
                        new
                        {
                            Id = 193,
                            Address = "Aut 30 de Mayo 12",
                            Latitude = 18.424544999999998,
                            Longitude = -69.989900000000006,
                            Name = "Cabañas Madrid"
                        },
                        new
                        {
                            Id = 194,
                            Address = "Av Cnel R T F Dguez 1 Km 2 1/2",
                            Latitude = 18.491056,
                            Longitude = -69.820379000000003,
                            Name = "Cabañas Miami"
                        },
                        new
                        {
                            Id = 195,
                            Address = "Carr S F V Tapia 30",
                            Latitude = 19.308399000000001,
                            Longitude = -70.286226999999997,
                            Name = "Cabañas Sabel"
                        },
                        new
                        {
                            Id = 196,
                            Address = "Aut San Isidro 1",
                            Latitude = 18.488672999999999,
                            Longitude = -69.823254000000006,
                            Name = "Cabañas Sol y Luna"
                        },
                        new
                        {
                            Id = 197,
                            Address = "",
                            Latitude = 19.445101999999999,
                            Longitude = -70.667468,
                            Name = "Cabañas Turísticas La Alborada"
                        },
                        new
                        {
                            Id = 198,
                            Address = "",
                            Latitude = 18.8903,
                            Longitude = -70.297399999999996,
                            Name = "Cabañas Turísticas La Grandiosa"
                        },
                        new
                        {
                            Id = 199,
                            Address = "Carr Las Guarañas Km 3 1/2",
                            Latitude = 19.262809000000001,
                            Longitude = -70.221090000000004,
                            Name = "Cabañas Turisticas Rubi"
                        },
                        new
                        {
                            Id = 200,
                            Address = "S Antonio 2",
                            Latitude = 18.590152,
                            Longitude = -69.840226999999999,
                            Name = "Hotel El Encuentro"
                        },
                        new
                        {
                            Id = 201,
                            Address = "Anacaona 13",
                            Latitude = 18.206696999999998,
                            Longitude = -71.106859999999998,
                            Name = "Hotel Las Magnolias"
                        },
                        new
                        {
                            Id = 202,
                            Address = "Av Anacaona Nte 94",
                            Latitude = 18.810300000000002,
                            Longitude = -71.231300000000005,
                            Name = "Hotel Medina"
                        },
                        new
                        {
                            Id = 203,
                            Address = "",
                            Latitude = 18.811026999999999,
                            Longitude = -71.230838000000006,
                            Name = "Hotel La Gran Posada"
                        },
                        new
                        {
                            Id = 204,
                            Address = "",
                            Latitude = 18.806403,
                            Longitude = -71.233583999999993,
                            Name = "Hotel Boutique El Espia"
                        },
                        new
                        {
                            Id = 205,
                            Address = "",
                            Latitude = 18.806642,
                            Longitude = -71.225590999999994,
                            Name = "Hotel Maguana"
                        },
                        new
                        {
                            Id = 206,
                            Address = "",
                            Latitude = 18.517099999999999,
                            Longitude = -69.807199999999995,
                            Name = "Hotel Pasión De Luna"
                        },
                        new
                        {
                            Id = 207,
                            Address = "S Antonio 2",
                            Latitude = 18.590152,
                            Longitude = -69.840226999999999,
                            Name = "Hotel Poderoso"
                        },
                        new
                        {
                            Id = 208,
                            Address = "A Meriño 31",
                            Latitude = 18.762640000000001,
                            Longitude = -69.034615000000002,
                            Name = "Motel Julling"
                        },
                        new
                        {
                            Id = 209,
                            Address = "Aut Duarte km 5 1/2",
                            Latitude = 19.418991999999999,
                            Longitude = -70.647807999999998,
                            Name = "Moteles Imperiales"
                        },
                        new
                        {
                            Id = 210,
                            Address = "Libertad 13",
                            Latitude = 19.321023,
                            Longitude = -69.540407000000002,
                            Name = "Paco Cabaña"
                        },
                        new
                        {
                            Id = 211,
                            Address = "",
                            Latitude = 19.321341,
                            Longitude = -69.538874000000007,
                            Name = "Residencia Del Paseo"
                        },
                        new
                        {
                            Id = 212,
                            Address = "",
                            Latitude = 19.322462999999999,
                            Longitude = -69.541967,
                            Name = "Condo Hotel Caribey"
                        },
                        new
                        {
                            Id = 213,
                            Address = "",
                            Latitude = 19.318985000000001,
                            Longitude = -69.540745000000001,
                            Name = "Hotel Piedra Marron"
                        },
                        new
                        {
                            Id = 214,
                            Address = "Carr Pto Pta-Stgo Km 2",
                            Latitude = 19.712177000000001,
                            Longitude = -70.622879999999995,
                            Name = "Super Cabañas Hollywood"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
